apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-vaultwarden
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  DOMAIN: {{ .Values.config.domain | quote }}
  SIGNUPS_ALLOWED: {{ .Values.config.signupsAllowed | quote }}
  SHOW_PASSWORD_HINT: {{ .Values.config.showPasswordHint | quote }}
  WEB_VAULT_ENABLED: {{ .Values.config.webVaultEnabled | quote }}
  SENDS_ALLOWED: {{ .Values.config.sendsAllowed | quote }}
  EMERGENCY_ACCESS_ALLOWED: {{ .Values.config.emergencyAccessAllowed | quote }}
  ORG_CREATION_USERS: {{ .Values.config.orgCreationUsers | quote }}
  ORG_GROUPS_ENABLED: {{ .Values.config.orgGroupsEnabled | quote }}
  ORG_EVENTS_ENABLED: {{ .Values.config.orgEventsEnabled | quote }}
  {{- if .Values.config.signupDomains }}
  SIGNUPS_DOMAINS_WHITELIST: {{ .Values.config.signupDomains | quote }}
  {{- end }}
  SIGNUPS_VERIFY: {{ .Values.config.signupsVerify | quote }}
  EMAIL_CHANGE_ALLOWED: {{ .Values.config.emailChangeAllowed | quote }}
  INVITATION_ORG_NAME: {{ .Values.config.invitationOrgName | quote }}
  INVITATION_EXPIRATION_HOURS: {{ .Values.config.invitationExpiration | quote }}
  REQUIRE_DEVICE_EMAIL: {{ .Values.config.requireDeviceEmail | quote }}
  SMTP_HOST: {{ .Values.smtp.host | quote }}
  SMTP_FROM: {{ .Values.smtp.from | quote }}
  SMTP_FROM_NAME: {{ .Values.smtp.fromName | quote }}
  SMTP_SECURITY: {{ .Values.smtp.security | quote }}
  SMTP_PORT: {{ .Values.smtp.port | quote }}
  SMTP_USERNAME: {{ .Values.smtp.username | quote }}
  {{- if .Values.storage.orgAttachmentLimit }}
  ORG_ATTACHMENT_LIMIT: {{ .Values.storage.orgAttachmentLimit | quote }}
  {{- end }}
  {{- if .Values.storage.userAttachmentLimit }}
  USER_ATTACHMENT_LIMIT: {{ .Values.storage.userAttachmentLimit | quote }}
  {{- end }}
  {{- if .Values.storage.sendStorageLimit }}
  SEND_STORAGE_LIMIT: {{ .Values.storage.sendStorageLimit | quote }}
  {{- end }}
  {{- if .Values.storage.trashAutoDeletion }}
  TRASH_AUTO_DELETE_DAYS: {{ .Values.storage.trashAutoDeletion | quote }}
  {{- end }}
  {{- if .Values.jobs.emergencyNotificationReminder }}
  EMERGENCY_NOTIFICATION_REMINDER_SCHEDULE: {{ .Values.jobs.emergencyNotificationReminder | quote }}
  {{- if .Values.jobs.emergencyAccessRequestTimeout }}
  EMERGENCY_REQUEST_TIMEOUT_SCHEDULE: {{ .Values.jobs.emergencyAccessRequestTimeout | quote }}
  {{- if .Values.jobs.eventCleanup }}
  EVENT_CLEANUP_SCHEDULE: {{ .Values.jobs.eventCleanup | quote }}
  {{- if .Values.jobs.eventRetentionDays }}
  EVENTS_DAYS_RETAIN: {{ .Values.jobs.eventRetentionDays | quote }}
  {{- if .Values.yubikey.clientId }}
  YUBICO_CLIENT_ID: {{ .Values.yubikey.clientId | quote }}
  {{- if .Values.yubikey.server }}
  YUBICO_SERVER: {{ .Values.yubikey.server | quote }}
  {{- if .Values.duo.iKey }}
  DUO_IKEY: {{ .Values.duo.iKey | quote }}
  {{- if .Values.duo.hostname }}
  DUO_HOST: {{ .Values.duo.hostname | quote }}
  SMTP_AUTH_MECHANISM: {{ .Values.smtp.authMechanism | quote }}
  SMTP_ACCEPT_INVALID_HOSTNAMES: {{ .Values.smtp.acceptInvalidHostnames | quote }}
  SMTP_ACCEPT_INVALID_CERTS: {{ .Values.smtp.acceptInvalidCerts | quote }}
  SMTP_DEBUG: {{ .Values.smtp.debug | quote }}
  {{- if .Values.sso.enabled }}
  SSO_ENABLED: {{ .Values.sso.enabled | toString | quote }}
  SSO_ONLY: {{ .Values.sso.onlySSO | toString | quote }}
  SSO_AUTHORITY: {{ .Values.sso.authority | quote }}
  SSO_CLIENT_ID: {{ .Values.sso.clientId | quote }}
  SSO_PKCE: {{ .Values.sso.pkce | toString | quote }}
  SSO_SCOPES: {{ .Values.sso.scopes | quote }}
  {{- if .Values.sso.masterPasswordPolicy }}
  SSO_MASTER_PASSWORD_POLICY: {{ .Values.sso.masterPasswordPolicy | quote }}
  {{- if .Values.pushNotifications.enabled }}
  PUSH_ENABLED: "true"
  {{- if .Values.pushNotifications.relayUri }}
  PUSH_RELAY_URI: {{ .Values.pushNotifications.relayUri | quote }}
  {{- if .Values.pushNotifications.identityUri }}
  PUSH_IDENTITY_URI: {{ .Values.pushNotifications.identityUri | quote }}
  ICON_SERVICE: {{ .Values.icons.service | quote }}
  ICON_REDIRECT_CODE: {{ .Values.icons.redirectCode | quote }}
  DISABLE_ICON_DOWNLOAD: {{ .Values.icons.disableLocalNetworkAccess | quote }}
  ADMIN_RATELIMIT_SECONDS: {{ .Values.admin.rateLimitSeconds | quote }}
  ADMIN_RATELIMIT_MAX_BURST: {{ .Values.admin.rateLimitMaxBurst | quote }}
  LOG_LEVEL: {{ .Values.logging.level | quote }}
  EXTENDED_LOGGING: {{ .Values.logging.timestamps | quote }}
  {{- if .Values.logging.file }}
  LOG_FILE: {{ .Values.logging.file | quote }}
