apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-vaultwarden
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  ADMIN_TOKEN: {{ .Values.secrets.adminToken | quote }}
  SMTP_PASSWORD: {{ .Values.secrets.smtpPassword | quote }}
  {{- if .Values.yubikey.secretKey }}
  YUBICO_SECRET_KEY: {{ .Values.yubikey.secretKey | quote }}
  {{- end }}
  {{- if .Values.duo.secretKey }}
  DUO_SKEY: {{ .Values.duo.secretKey | quote }}
  {{- end }}
  {{- if and .Values.sso.enabled .Values.sso.clientSecret }}
  SSO_CLIENT_SECRET: {{ .Values.sso.clientSecret | quote }}
  {{- if .Values.pushNotifications.enabled }}
  {{- if .Values.pushNotifications.installationId }}
  PUSH_INSTALLATION_ID: {{ .Values.pushNotifications.installationId | quote }}
  {{- if .Values.pushNotifications.installationKey }}
  PUSH_INSTALLATION_KEY: {{ .Values.pushNotifications.installationKey | quote }}
  {{- if ne .Values.database.type "sqlite" }}
  {{- if .Values.database.uri }}
  DATABASE_URL: {{ .Values.database.uri | quote }}
  {{- else }}
  DATABASE_URL: {{ printf "%s://%s:%s@%s:%s/%s" .Values.database.type .Values.database.username .Values.database.password .Values.database.host .Values.database.port .Values.database.name | quote }}
  {{- if .Values.hibp.apiKey }}
  HIBP_API_KEY: {{ .Values.hibp.apiKey | quote }}
